-- migrate:up

CREATE TABLE "if__deployments" (
    uuid uuid generated always as (((doc ->> 'uuid'::text))::uuid) stored not null,
    doc jsonb not null,
    nonce bytea generated always as ( decode( md5((doc - 'uuid')::text), 'hex')) stored,
    created_at timestamp with time zone default CURRENT_TIMESTAMP,
    updated_at timestamp with time zone default CURRENT_TIMESTAMP,
    service text generated always as (doc->>'service') stored,
    name text generated always as (doc->>'name') stored,
    description text generated always as (doc->>'description') stored,
    PRIMARY KEY ("uuid")
);

CREATE INDEX idx_service ON if__deployments ("service");
CREATE INDEX idx_name ON if__deployments ("name");
ALTER TABLE "if__deployments" ADD CONSTRAINT unique_nonce UNIQUE (nonce);

COMMENT ON TABLE "if__deployments" IS 'Integration framework service deployments.';
COMMENT ON COLUMN "if__deployments"."uuid" IS 'IF service deployment uuid, autogenerated on SQL insert if not provided.';
COMMENT ON COLUMN "if__deployments"."doc" IS 'Connection configuration, i.e. host, port, token, password, etc. (encrypted)';
COMMENT ON COLUMN "if__deployments"."nonce" IS 'MD5 hash of (doc - uuid) to track changes to the document or act as a unique index';
COMMENT ON COLUMN "if__deployments"."service" IS 'Service type';
COMMENT ON COLUMN "if__deployments"."name" IS 'Deployment name';
COMMENT ON COLUMN "if__deployments"."description" IS 'Deployment description';

-- migrate:down

DROP TABLE "if__deployments" CASCADE;