-- migrate:up

CREATE TABLE `t_if__logs` (
  `c_act_uuid` binary(16) NOT NULL COMMENT 'IF instance uuid (v4), autogenerated on SQL insert if not provided. NOTE to always insert with UUID_TO_BIN(UUID(), true)',
  `c_uuid` binary(16) NOT NULL DEFAULT (uuid_to_bin(uuid(),true)) COMMENT 'IF instance logline uuid (v4), autogenerated on SQL insert if not provided. NOTE to always insert with UUID_TO_BIN(UUID(), true)',
  `c_data` json NOT NULL COMMENT 'JSON response body (files will be attached to stor by c_svc_uuid/c_uuid',
  `c_ts_requested` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp: requested',
  `c_ts_responded` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp: responded',
  `c_ok` tinyint(1) DEFAULT NULL COMMENT 'Integration run success/fail',
  `c_response_hash` varchar(255) DEFAULT NULL COMMENT 'Response data hash',
  `c_response_fid` varchar(255) DEFAULT NULL COMMENT 'Response foreign identifier',
  PRIMARY KEY (`c_uuid`),
  KEY `idx_act_uuid` (`c_act_uuid`),
  KEY `idx_response_hash` (`c_response_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='Integration framework service logs.';

-- migrate:down

DROP TABLE IF EXISTS `t_if__logs`;
