-- migrate:up

CREATE TABLE `t_if__actions` (
  `c_svc_uuid` binary(16) NOT NULL COMMENT 'IF instance uuid (v4), autogenerated on SQL insert if not provided. NOTE to always insert with UUID_TO_BIN(UUID(), true)',
  `c_uuid` binary(16) NOT NULL DEFAULT (uuid_to_bin(uuid(),true)) COMMENT 'IF action uuid (v4), autogenerated on SQL insert if not provided. NOTE to always insert with UUID_TO_BIN(UUID(), true)',
  `c_data` json NOT NULL COMMENT 'JSON data',
  `c_type` varchar(255) GENERATED ALWAYS AS (json_unquote(json_extract(`c_data`,_utf8mb4'$.type'))) STORED COMMENT '[STORED] Interface Framework action type',
  `c_note` varchar(255) GENERATED ALWAYS AS (json_unquote(json_extract(`c_data`,_utf8mb4'$.note'))) STORED COMMENT '[STORED] Interface Framework action note',
  `c_freq` varchar(255) GENERATED ALWAYS AS (json_unquote(json_extract(`c_data`,_utf8mb4'$.freq'))) STORED COMMENT '[STORED] Interface Framework action frequency',
  PRIMARY KEY (`c_uuid`),
  UNIQUE KEY `uniq_svc_uuid_type` (`c_svc_uuid`,`c_type`),
  KEY `idx_svc_uuid` (`c_svc_uuid`),
  KEY `idx_type` (`c_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='Integration framework service instance actions.';

-- migrate:down

DROP TABLE IF EXISTS `t_if__actions`;
