-- migrate:up

CREATE TABLE `t_if__actions` (
  `c_svc_uuid` binary(16) NOT NULL COMMENT 'IF instance uuid (v4), autogenerated on SQL insert if not provided. NOTE to always insert with UUID_TO_BIN(UUID(), true)',
  `c_uuid` binary(16) NOT NULL DEFAULT (uuid_to_bin(uuid(),true)) COMMENT 'IF action uuid (v4), autogenerated on SQL insert if not provided. NOTE to always insert with UUID_TO_BIN(UUID(), true)',
  `c_data` json NOT NULL COMMENT 'JSON data',
  `c_type` varchar(255) GENERATED ALWAYS AS (json_unquote(json_extract(`c_data`,_utf8mb4'$.type'))) STORED COMMENT '[STORED] Interface Framework action type',
  `c_note` varchar(255) GENERATED ALWAYS AS (json_unquote(json_extract(`c_data`,_utf8mb4'$.note'))) STORED COMMENT '[STORED] Interface Framework action note',
  `c_freq` varchar(255) GENERATED ALWAYS AS (json_unquote(json_extract(`c_data`,_utf8mb4'$.freq'))) STORED COMMENT '[STORED] Interface Framework action frequency',
  PRIMARY KEY (`c_uuid`),
  KEY `idx_svc_uuid` (`c_svc_uuid`),
  KEY `idx_type` (`c_type`),
  UNIQUE KEY `uniq_svc_uuid_type` (`c_svc_uuid`, `c_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='Integration framework service instance actions.';


CREATE TABLE `t_if__services` (
  `c_uuid` binary(16) NOT NULL DEFAULT (uuid_to_bin(uuid(),true)) COMMENT 'IF service instance uuid (v4), autogenerated on SQL insert if not provided. NOTE to always insert with UUID_TO_BIN(UUID(), true)',
  `c_data` json NOT NULL COMMENT 'JSON data',
  `c_hash` varchar(32) GENERATED ALWAYS AS (MD5(`c_data`)) STORED COMMENT '[STORED] MD5 Hash of the data json (acting as a unique index)',
  `c_type` varchar(255) GENERATED ALWAYS AS (json_unquote(json_extract(`c_data`,_utf8mb4'$.type'))) STORED COMMENT '[STORED] Interface Framework service type',
  `c_name` varchar(255) GENERATED ALWAYS AS (json_unquote(json_extract(`c_data`,_utf8mb4'$.name'))) STORED COMMENT '[STORED] Interface Framework service deployment name',
  `c_host` varchar(255) GENERATED ALWAYS AS (json_unquote(json_extract(`c_data`,_utf8mb4'$.host'))) STORED COMMENT '[STORED] Interface Framework remote host',
  `c_note` varchar(255) GENERATED ALWAYS AS (json_unquote(json_extract(`c_data`,_utf8mb4'$.note'))) STORED COMMENT '[STORED] Interface Framework remote note',
  PRIMARY KEY (`c_uuid`),
  UNIQUE (`c_hash`),
  KEY `idx_type` (`c_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='Integration framework service instances (service / remote host / authentication).';


CREATE TABLE `t_if__logs` (
  `c_act_uuid` binary(16) NOT NULL COMMENT 'IF instance uuid (v4), autogenerated on SQL insert if not provided. NOTE to always insert with UUID_TO_BIN(UUID(), true)',
  `c_uuid` binary(16) NOT NULL DEFAULT (uuid_to_bin(uuid(),true)) COMMENT 'IF instance logline uuid (v4), autogenerated on SQL insert if not provided. NOTE to always insert with UUID_TO_BIN(UUID(), true)',
  `c_data` json NOT NULL COMMENT 'JSON response body (files will be attached to stor by c_svc_uuid/c_uuid',
  `c_ts_requested` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp: requested',
  `c_ts_responded` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp: responded',
  `c_ok` tinyint(1) NULL DEFAULT NULL COMMENT 'Integration run success/fail',
  `c_response_hash` varchar(255) NULL COMMENT 'Response data hash',
  `c_response_fid` varchar(255) NULL COMMENT 'Response foreign identifier',
  PRIMARY KEY (`c_uuid`),
  INDEX idx_act_uuid (`c_act_uuid`),
  INDEX idx_response_hash (`c_response_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='Integration framework service logs.';

-- migrate:down

DROP TABLE IF EXISTS `t_if__logs`;
DROP TABLE IF EXISTS `t_if__actions`;
DROP TABLE IF EXISTS `t_if__services`;
