---
routes:

    #########################################################
    # IF / NODES                                            #
    #########################################################

    be_if:
        service:    if
        path:       /api/if
        pattern:    /api/if
        label:      IF
        dscr:       A routegroup, no methods here.

    #########################################################
    # IF / HEALTH                                           #
    #########################################################

    be_if_health_v1:
        pattern:    ${routes.be_if.path}/health/v1
        path:       ${routes.be_if.path}/health/v1
        label:      if health
        dscr:       A healthcheck endpoint for the integration framework microservice.
        service:    IF
        provides:   health
        methods:
            get:    Glued\Controllers\IfController:health

    #########################################################
    # IF / SERVICES                                         #
    #########################################################

    be_if_services_v1:
        pattern:    ${routes.be_if.path}/services/v1
        path:       ${routes.be_if.path}/services/v1
        label:      IF Services
        dscr:       People-friendly navigation.
        service:    if
        methods:
            get:    Glued\Controllers\IfController:services_r1
            post:   Glued\Controllers\IfController:services_c1

    be_if_queue_v1:
        pattern:    ${routes.be_if.path}/queue/v1
        path:       ${routes.be_if.path}/queue/v1
        label:      IF Queue
        dscr:       Interface queue
        service:    if
        methods:
            get:    Glued\Controllers\IfController:queue_r1

    be_if_stats_v1:
        pattern:    ${routes.be_if.path}/stats/v1
        path:       ${routes.be_if.path}/stats/v1
        label:      IF Statistics
        dscr:       Interface statistics
        service:    if
        methods:
            get:    Glued\Controllers\IfController:stats_r1

    be_if_logs_v1:
        pattern:    ${routes.be_if.path}/logs/v1
        path:       ${routes.be_if.path}/logs/v1
        label:      IF Logs
        dscr:       Interface logs
        service:    if
        methods:
            get:    Glued\Controllers\IfController:logs_r1

    be_if_reg_v1:
        pattern:    ${routes.be_if.path}/reg/v1
        path:       ${routes.be_if.path}/reg/v1
        label:      IF Register
        dscr:       Interface action register
        service:    if
        methods:
            get:    Glued\Controllers\IfController:reg_r1