---
routes:

    #########################################################
    # IF / NODES                                            #
    #########################################################

    be_if:
        service:    if
        path:       /api/if
        pattern:    /api/if
        label:      IF
        dscr:       A routegroup, no methods here.

    #########################################################
    # IF / HEALTH                                           #
    #########################################################

    be_if_health:
        pattern:    ${routes.be_if.path}/v1/health
        path:       ${routes.be_if.path}/v1/health
        label:      if health
        dscr:       A healthcheck endpoint for the integration framework microservice.
        service:    IF
        provides:   health
        methods:
            get:    Glued\Controllers\IfController:health

    #########################################################
    # IF / SERVICES                                         #
    #########################################################
    # service is the microservice
    # deployment is the host/auth combination
    # actions are the runnable activities within a deployment

    be_if_hello:
        pattern:    ${routes.be_if.path}/v1/hello
        path:       ${routes.be_if.path}/v1/hello
        label:      IF Hello
        dscr:       People-friendly navigation.
        service:    if
        methods:
            get:    Glued\Controllers\IfController:hello_r1


    be_if_services:
        pattern:    ${routes.be_if.path}/v1/services
        path:       ${routes.be_if.path}/v1/services
        label:      IF Services
        dscr:       Services
        service:    if
        methods:
            get:    Glued\Controllers\IfController:services_r1

    be_if_deployments:
        pattern:    ${routes.be_if.path}/v1/deployments[/{deploy}]
        path:       ${routes.be_if.path}/v1/deployments
        label:      IF Services
        dscr:       People-friendly navigation.
        service:    if
        methods:
            get:    Glued\Controllers\IfController:deployments_r1
            post:   Glued\Controllers\IfController:deployments_c1

    be_if_scheduler:
        pattern:    ${routes.be_if.path}/v1/scheduler
        path:       ${routes.be_if.path}/v1/scheduler
        label:      IF Queue
        dscr:       Interface queue
        service:    if
        methods:
            get:    Glued\Controllers\IfController:queue_r1

    be_if_stats:
        pattern:    ${routes.be_if.path}/v1/stats
        path:       ${routes.be_if.path}/v1/stats
        label:      IF Statistics
        dscr:       Interface statistics
        service:    if
        methods:
            get:    Glued\Controllers\IfController:stats_r1

    be_if_runs:
        pattern:    ${routes.be_if.path}/v1/runs
        path:       ${routes.be_if.path}/v1/runs
        label:      IF runs
        dscr:       Interface runs
        service:    if
        methods:
            get:    Glued\Controllers\IfController:runs_r1
